Repository vueuse/vueuse, pull requests merged in 2023-03, with the labels that each got.

#2656 refactor!: remove deprecated types
  packages/shared/utils/types.ts
Labels: BREAKING CHNAGE

#2168 feat(useBrowserLocation): two-way binding
  packages/core/useBrowserLocation/demo.vue
  packages/core/useBrowserLocation/index.ts
  packages/shared/utils/index.ts
Labels: BREAKING CHNAGE, no stale

#2474 feat(useIDBKeyval)!: return format changed, add `isFinished`
  packages/integrations/useIDBKeyval/index.md
  packages/integrations/useIDBKeyval/index.test.ts
  packages/integrations/useIDBKeyval/index.ts
Labels: BREAKING CHNAGE

#2807 fix(useAxios)!: `error` should return type `unknown`
  packages/integrations/useAxios/index.test.ts
  packages/integrations/useAxios/index.ts
Labels: BREAKING CHNAGE

#2621 feat(computedAsync)!: set shallow defalut to true
  packages/core/computedAsync/index.md
  packages/core/computedAsync/index.ts
Labels: BREAKING CHNAGE

#2790 feat(createGlobalState): allow passing initial args
  packages/shared/createGlobalState/index.ts
Labels: direction: approved

#2651 feat(watch): shorthands for watch
  packages/shared/index.ts
  packages/shared/watchDeep/index.md
  packages/shared/watchDeep/index.test.ts
  packages/shared/watchDeep/index.ts
  packages/shared/watchImmediate/index.md
  packages/shared/watchImmediate/index.test.ts
  packages/shared/watchImmediate/index.ts
Labels: direction: approved

#2748 fix(useEventBus,createEventHook)!: dedupe registration of the same function
  packages/core/useEventBus/index.test.ts
  packages/core/useEventBus/index.ts
  packages/shared/createEventHook/index.test.ts
  packages/shared/createEventHook/index.ts
Labels: BREAKING CHNAGE, direction: approved

#2743 feat(useTransition): expose transition utility for manual control
  packages/core/useTransition/index.md
  packages/core/useTransition/index.test.ts
  packages/core/useTransition/index.ts
Labels: direction: approved

#2710 feat(useArrayDifference): new function
  packages/shared/index.ts
  packages/shared/useArrayDifference/index.md
  packages/shared/useArrayDifference/index.test.ts
  packages/shared/useArrayDifference/index.ts
Labels: direction: approved

#2708 feat(useArrayIncludes): new function
  packages/shared/index.ts
  packages/shared/useArrayIncludes/index.md
  packages/shared/useArrayIncludes/index.test.ts
  packages/shared/useArrayIncludes/index.ts
Labels: direction: approved

#2736 feat(usePerformanceObserver): new function
  packages/core/index.ts
  packages/core/usePerformanceObserver/demo.vue
  packages/core/usePerformanceObserver/index.md
  packages/core/usePerformanceObserver/index.ts
Labels: direction: approved

#2763 feat(useSortable): new function
  packages/add-ons.md
  packages/integrations/README.md
  packages/integrations/index.ts
  packages/integrations/package.json
  packages/integrations/useSortable/component.ts
  packages/integrations/useSortable/demo.vue
  packages/integrations/useSortable/index.md
  packages/integrations/useSortable/index.ts
  pnpm-lock.yaml
Labels: direction: approved

#2687 refactor(useAxios): refactor `AxiosRequestConfig` type
  packages/integrations/useAxios/index.ts
Labels: direction: approved

#2893 feat(useFileDialog): add listener for file change events
  packages/core/useFileDialog/demo.vue
  packages/core/useFileDialog/index.md
  packages/core/useFileDialog/index.ts
Labels: direction: approved

#2652 feat(onKeyStroke): support ignoring repeated stroke
  packages/core/onKeyStroke/demo.vue
  packages/core/onKeyStroke/index.md
  packages/core/onKeyStroke/index.test.ts
  packages/core/onKeyStroke/index.ts
Labels: direction: approved

#2612 feat(useArrayUnique): add a custom function to deduplicate
  packages/shared/useArrayUnique/index.md
  packages/shared/useArrayUnique/index.test.ts
  packages/shared/useArrayUnique/index.ts
Labels: direction: approved
