Repository vueuse/vueuse, pull requests merged in 2024-10, with the labels that each got.

#4274 docs(useSortable): fix typo
  packages/integrations/useSortable/index.md
Labels: documentation, size:XS, lgtm

#4276 docs: wording
  packages/shared/computedEager/index.md
Labels: documentation, size:XS

#4271 docs(watchImmediate): corrected variable name in example
  packages/shared/watchImmediate/index.md
Labels: documentation, size:XS, lgtm

#4253 feat(useMediaControls): add playback error event
  packages/core/useMediaControls/index.ts
Labels: enhancement, size:S, lgtm

#4261 fix(useManualRefHistory): `canUndo` and `canRedo` typing to be computed ref
  packages/core/useManualRefHistory/index.ts
Labels: size:XS, lgtm

#4246 fix(useDevicesList): handle NotAllowedError on reject/close
  packages/core/useDevicesList/index.ts
Labels: size:S, lgtm

#4243 fix(useArrayReduce): initialValue can be a function
  packages/shared/useArrayReduce/index.test.ts
  packages/shared/useArrayReduce/index.ts
Labels: size:S, lgtm

#4238 feat(useBreakpoints): add breakpoints for ElementUI/ElementPlus
  packages/core/useBreakpoints/breakpoints.ts
  packages/core/useBreakpoints/index.md
Labels: enhancement, size:S, lgtm

#4258 fix(useIntervalFn): prevent timer being set after pause is called in cb
  packages/shared/useIntervalFn/index.test.ts
  packages/shared/useIntervalFn/index.ts
Labels: size:S, lgtm

#4305 fix(useDropZone): remove file kind restriction
  packages/core/useDropZone/index.ts
Labels: size:XS, lgtm

#4314 fix(useWebSocket): autoreconnect when ws close
  packages/core/useWebSocket/index.ts
Labels: size:XS, lgtm

#4233 docs(useVirtualList): add props.index for quick understanding
  packages/core/useVirtualList/index.md
Labels: documentation, size:XS

#4303 docs: update nuxt readme to show all disabled functions
  packages/nuxt/README.md
Labels: documentation, size:XS
