Repository vueuse/vueuse, pull requests merged in 2024-12, with the labels that each got.

#4401 docs(useVModel): add hint to defineModel
  packages/core/useVModel/index.md
Labels: documentation, size:XS, lgtm

#4400 docs(watchIgnorable): update author link of recommended reading
  packages/shared/watchIgnorable/index.md
Labels: documentation, size:XS, lgtm

#4402 docs: add team and contributor info
  packages/contributors.json
  packages/contributors.ts
  scripts/utils.ts
Labels: documentation, size:S

#4404 test: add useWebSocket tests
  packages/core/useWebSocket/index.test.ts
Labels: size:L, lgtm

#4316 feat(useBase64): add options for Data URL output control
  packages/core/useBase64/index.ts
Labels: enhancement, size:S, lgtm

#4403 fix(useMediaQuery): the return value should be computed
  packages/core/useColorMode/index.test.ts
  packages/core/useMediaQuery/index.ts
Labels: size:S, lgtm

#4407 chore: fix issue template title convention escaping
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size:XS

#4411 docs(useClipboardItems): display current copied value with content
  packages/core/useClipboardItems/index.md
Labels: size:XS

#4370 docs(useClipboardItems): fix example
  packages/core/useClipboardItems/index.md
Labels: documentation, size:XS

#4019 fix(useWebNotification): prevent notifications when checking for support
  packages/core/useWebNotification/index.ts
Labels: size:S, lgtm

#4378 feat(createEventHook): add `clear` function
  packages/shared/createEventHook/index.test.ts
  packages/shared/createEventHook/index.ts
Labels: enhancement, size:M, lgtm

#4418 chore: replace fast-glob
  package.json
  packages/metadata/scripts/update.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  rollup.config.ts
  scripts/build.ts
Labels: dependencies, size:S, lgtm

#4413 chore: remove rimraf
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies, size:XS, lgtm

#4116 feat(useWebsocket): support ref or getter as message
  packages/core/useWebSocket/index.ts
Labels: enhancement, size:S, lgtm

#4417 feat(useWebSocket): introduce `autoConnect` options to control auto connections on url changes
  packages/core/useWebSocket/index.md
  packages/core/useWebSocket/index.test.ts
  packages/core/useWebSocket/index.ts
Labels: size:M, lgtm

#4050 docs(useDevicesList): add permissions request example
  packages/core/useDevicesList/index.md
Labels: documentation, size:S, needs refactor

#4133 fix(useScroll): to properly report arriveState for elastic scroll
  packages/core/useScroll/index.ts
Labels: size:S, lgtm

#3977 fix(useRouteParams,useRouteQuery): set route param/query to undefined when defaultValue is ref or getter
  packages/router/useRouteParams/index.ts
  packages/router/useRouteQuery/index.test.ts
  packages/router/useRouteQuery/index.ts
Labels: size:S, lgtm

#4129 fix(useTextareaAutosize): Make input defaults as expected
  packages/core/useTextareaAutosize/index.ts
Labels: size:XS, lgtm

#4294 fix(useAsyncState): use ShallowRef instead of Ref type
  packages/core/useAsyncState/index.ts
Labels: size:XS, lgtm

#4100 feat(useElementVisibility): add `rootMargin` option
  packages/core/useElementVisibility/directive.test.ts
  packages/core/useElementVisibility/index.md
  packages/core/useElementVisibility/index.ts
Labels: size:S, needs refactor

#4395 feat(useWindowSize): add `type: visual` option that leverage `visualViewport`
  packages/core/useWindowSize/index.ts
Labels: enhancement, size:S, lgtm

#4392 feat(useUrlSearchParams): add `writeMode` options
  packages/core/useUrlSearchParams/index.test.ts
  packages/core/useUrlSearchParams/index.ts
Labels: enhancement, size:M, lgtm

#4319 fix(useDropZone): update type to allow readonly array param
  packages/core/useDropZone/index.ts
Labels: size:XS, lgtm

#4317 feat(useSSRWidth): add optional support for SSR in useMediaQuery and useBreakpoints
  packages/core/index.ts
  packages/core/useBreakpoints/index.md
  packages/core/useBreakpoints/index.test.ts
  packages/core/useBreakpoints/index.ts
  packages/core/useMediaQuery/index.md
  packages/core/useMediaQuery/index.test.ts
  packages/core/useMediaQuery/index.ts
  packages/core/useSSRWidth/index.md
  packages/core/useSSRWidth/index.test.ts
  packages/core/useSSRWidth/index.ts
  packages/shared/utils/index.ts
Labels: enhancement, size:L, lgtm

#4406 docs: add bluesky and replace twitter with x branding
  packages/.vitepress/config.ts
  packages/.vitepress/theme/components/TeamMember.vue
  packages/contributors.ts
Labels: documentation, size:S

#4374 docs(onKeyStroke): demo from preventing w and s keypress in global search.
  packages/core/onKeyStroke/demo.vue
Labels: direction: approved, size:S

#4344 feat(useMediaControls): add 'media' option to define media query for resources
  packages/core/useMediaControls/index.ts
Labels: enhancement, size:XS, lgtm

#4229 fix(useWebSocket): close socket connection inside webworker fix
  packages/core/useWebSocket/index.ts
Labels: size:XS

#4366 fix(useFetch): handle empty payload
  packages/core/useFetch/index.ts
Labels: size:XS, lgtm

#4409 feat(useRafFn): allow framerate to be a reactive value
  packages/core/useRafFn/index.test.ts
  packages/core/useRafFn/index.ts
Labels: enhancement, size:L, lgtm

#4414 chore: remove fs-extra
  package.json
  packages/.vitepress/plugins/markdownTransform.ts
  packages/metadata/scripts/update.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/build.ts
  scripts/export-size.ts
  scripts/redirects.ts
  scripts/release.ts
  scripts/update.ts
  scripts/utils.ts
Labels: dependencies, size:M, lgtm

#4421 test: replace timeouts with fake timers
  packages/core/computedAsync/index.test.ts
  packages/core/onLongPress/index.test.ts
  packages/core/useConfirmDialog/index.test.ts
  packages/core/useCssVar/index.test.ts
  packages/core/useDebouncedRefHistory/index.test.ts
  packages/core/useFetch/index.test.ts
  packages/core/useMutationObserver/index.test.ts
  packages/core/useNow/index.test.ts
  packages/core/useStorage/index.test.ts
  packages/core/useThrottledRefHistory/index.test.ts
  packages/core/useTimeAgo/index.test.ts
  packages/core/useTimeoutPoll/index.test.ts
  packages/core/useTimestamp/index.test.ts
  packages/core/useWakeLock/index.test.ts
  packages/integrations/useAxios/index.test.ts
  packages/integrations/useIDBKeyval/index.test.ts
  packages/rxjs/useExtractedObservable/index.test.ts
  packages/rxjs/watchExtractedObservable/index.test.ts
  packages/shared/createEventHook/index.test.ts
  packages/shared/refAutoReset/index.test.ts
  packages/shared/until/index.test.ts
  packages/shared/useIntervalFn/index.test.ts
  packages/shared/useThrottleFn/index.test.ts
  packages/shared/useTimeout/index.test.ts
  packages/shared/useTimeoutFn/index.test.ts
  packages/shared/watchDebounced/index.test.ts
  packages/shared/watchThrottled/index.test.ts
Labels: size:L

#4383 fix(useWebSocket): clear retryTimer when connected
  packages/core/useWebSocket/index.ts
Labels: direction: approved, size:S, lgtm

#4146 feat(useArrayDifference): new `symmetric` option
  packages/shared/useArrayDifference/index.md
  packages/shared/useArrayDifference/index.test.ts
  packages/shared/useArrayDifference/index.ts
Labels: size:M, lgtm

#4173 feat(useImage): support more native option
  packages/core/useImage/component.ts
  packages/core/useImage/index.ts
Labels: enhancement, size:M, lgtm

#4204 feat(useEventSource): new `autoConnect` option to align with `useWebSocket`
  packages/core/useEventSource/index.md
  packages/core/useEventSource/index.ts
  packages/core/useWebSocket/index.ts
Labels: documentation, size:M, lgtm

#4201 feat(usePreferredReducedTransparency): add new function
  packages/components/index.ts
  packages/core/index.ts
  packages/core/usePreferredReducedTransparency/component.ts
  packages/core/usePreferredReducedTransparency/demo.vue
  packages/core/usePreferredReducedTransparency/index.md
  packages/core/usePreferredReducedTransparency/index.ts
Labels: new function, size:M, lgtm

#4420 test(useTextDirection): add basic test suits
  packages/core/useTextDirection/index.test.ts
  vitest.config.ts
Labels: size:M, lgtm, test suites

#4422 build: improve dist structure
  .gitignore
  FUNDING.json
  eslint.config.js
  meta/packages.ts
  package.json
  packages/components/package.json
  packages/components/rollup.config.ts
  packages/core/package.json
  packages/core/rollup.config.ts
  packages/electron/package.json
  packages/electron/rollup.config.ts
  packages/export-size.json
  packages/export-size.md
  packages/firebase/package.json
  packages/firebase/rollup.config.ts
  packages/integrations/package.json
  packages/integrations/rollup.config.ts
  packages/math/package.json
  packages/math/rollup.config.ts
  packages/metadata/package.json
  packages/metadata/rollup.config.ts
  packages/nuxt/package.json
  packages/nuxt/rollup.config.ts
  packages/router/package.json
  packages/router/rollup.config.ts
  packages/rxjs/package.json
  packages/rxjs/rollup.config.ts
  packages/shared/package.json
  packages/shared/rollup.config.ts
  playgrounds/nuxt/package.json
  playgrounds/vite/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  rollup.config.ts
  scripts/build.ts
  scripts/clean.ts
  scripts/export-size.ts
  scripts/publish.ts
  scripts/utils.ts
Labels: build tools, size:XXL

#4423 docs(useSortable): add restriction warning
  packages/integrations/useSortable/index.md
Labels: documentation, size:XS, lgtm

#4235 docs(usePermission): add `geolocation` to demo
  packages/core/usePermission/demo.vue
Labels: documentation, size:XS, lgtm

#4292 docs(useDraggable): example for `preventDefault: true`
  packages/core/useDraggable/index.md
Labels: documentation, size:S

#4425 feat(useMousePressed): add `onPressed` and `onReleased` as options
  packages/core/useMousePressed/index.ts
Labels: enhancement, size:M, lgtm

#4325 fix(useDropZone): validate all file types individually when dropping multiple files
  packages/core/useDropZone/demo.vue
  packages/core/useDropZone/index.md
  packages/core/useDropZone/index.ts
Labels: size:M, lgtm

#4299 fix(useClipboard,useClipboardItems): avoid running "copied" timeout during initialization
  packages/core/useClipboard/index.ts
  packages/core/useClipboardItems/index.ts
Labels: size:XS, lgtm

#4382 fix(useRouteQuery): differentiate `undefined` and `null` when writing value
  packages/router/useRouteQuery/index.test.ts
  packages/router/useRouteQuery/index.ts
Labels: size:M, lgtm

#4424 feat(useWindowScroll): use `useScroll` under the hood
  packages/core/useScroll/index.test.ts
  packages/core/useScroll/index.ts
  packages/core/useWindowScroll/index.test.ts
  packages/core/useWindowScroll/index.ts
Labels: enhancement, size:L, lgtm

#4394 fix(useFocusWithin): correctly track the state when switching the focus of elements in the same container
  packages/core/useFocusWithin/index.test.ts
  packages/core/useFocusWithin/index.ts
Labels: size:S, lgtm

#4419 fix(useAxios): narrow type of data when initialValue is provided
  packages/integrations/useAxios/index.test.ts
  packages/integrations/useAxios/index.ts
Labels: size:M, lgtm

#4119 fix(useSpeechRecognition): execute 'start' when not ended
  packages/core/useSpeechRecognition/index.ts
Labels: size:S, lgtm

#4429 docs: remove ie 11 notes
  packages/.vitepress/theme/components/RequiresProxy.vue
  packages/core/onClickOutside/index.md
  packages/core/useMagicKeys/index.md
  packages/shared/reactiveComputed/index.md
  packages/shared/toReactive/index.md
Labels: documentation, size:S

#4435 docs: new team page, introduce Team Emeriti
  packages/.vitepress/config.ts
  packages/.vitepress/theme/components/Home.vue
  packages/.vitepress/theme/components/HomeContributors.vue
  packages/.vitepress/theme/components/HomeSection.vue
  packages/.vitepress/theme/components/HomeSponsors.vue
  packages/.vitepress/theme/components/HomeTeam.vue
  packages/.vitepress/theme/components/TeamMember.vue
  packages/.vitepress/theme/components/TeamMembersGrid.vue
  packages/contributors.ts
  packages/team.md
Labels: documentation, size:L

#4440 test: add browser tests with `*.browser.test.ts` files
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  package.json
  packages/core/useAnimate/index.browser.test.ts
  pnpm-lock.yaml
  tsconfig.json
  vitest.config.ts
  vitest.workspace.ts
Labels: size:L, lgtm

#4446 docs: add support for client-side redirects for old functions paths
  packages/.vitepress/theme/index.ts
Labels: documentation, size:S
