Repository vueuse/vueuse, pull requests merged in 2024-02, with the labels that each got.

#3616 fix(useFetch): mark `isFinished`, `isFetching` readonly
  packages/core/useFetch/index.ts
Labels: size:S, lgtm

#3788 feat(createInjectionState): injectionKey use composable name
  packages/shared/createInjectionState/index.ts
Labels: size:XS, lgtm

#3768 fix(useDraggable): avoid moving out of container
  packages/core/useDraggable/index.ts
Labels: size:XS, lgtm

#3641 fix(createReusableTemplate): improve types
  packages/core/createReusableTemplate/index.ts
Labels: size:M, lgtm

#3621 feat(useBreakpoints): enable passing ref or getter to get breakpoints
  packages/core/useBreakpoints/demo.vue
  packages/core/useBreakpoints/index.ts
Labels: lgtm

#3653 fix(useGamepad): explicitly ensure gamepad index is available
  packages/core/useGamepad/index.ts
Labels: lgtm

#3775 fix(useGamepad): improve data updating logic
  packages/core/useGamepad/index.ts
Labels: lgtm

#3780 fix(useFileSystemAccess): updateData on modified file
  packages/core/useFileSystemAccess/demo.vue
  packages/core/useFileSystemAccess/index.ts
Labels: lgtm

#3722 feat(throttleFilter): support object as argument
  packages/shared/utils/filters.ts
  packages/shared/utils/index.test.ts
Labels: size:L, lgtm

#3783 feat(useBreakpoints): add `strategy` option to allow desktop-first convention
  packages/core/useBreakpoints/index.ts
Labels: size:M, lgtm

#3741 feat(useMutationObserver): allow multiple targets
  packages/core/useMutationObserver/index.test.ts
  packages/core/useMutationObserver/index.ts
Labels: lgtm

#3613 feat(useDraggable): add disabled parameter
  packages/core/useDraggable/component.ts
  packages/core/useDraggable/demo.vue
  packages/core/useDraggable/index.ts
Labels: lgtm

#3763 fix(useAnimate): immediate option set false not working
  packages/core/useAnimate/index.ts
Labels: size:XS, lgtm

#3750 feat(useCurrentElement): Allow get current element from a specific component
  packages/core/useCurrentElement/index.md
  packages/core/useCurrentElement/index.test.ts
  packages/core/useCurrentElement/index.ts
Labels: size:M, lgtm

#3606 feat(nuxt): move to ESM-first and fix types
  packages/metadata/package.json
  packages/nuxt/index.cjs
  packages/nuxt/package.json
  scripts/utils.ts
Labels: lgtm

#3757 fix(useUserMedia): stop stream on scope dispose
  packages/core/useUserMedia/index.ts
Labels: lgtm

#3675 feat(useParallax): can work with different screen orientation
  packages/core/useParallax/index.ts
Labels: lgtm

#3615 feat(useCycleList): add `go` function
  packages/core/useCycleList/index.md
  packages/core/useCycleList/index.test.ts
  packages/core/useCycleList/index.ts
Labels: size:S, lgtm

#3707 fix(useWebSocket): reset `wsRef` on close, fix #3706
  packages/core/useWebSocket/index.ts
Labels: lgtm

#3715 fix(useElementVisiblity): allow configuring `threshold`
  packages/core/useElementVisibility/index.test.ts
  packages/core/useElementVisibility/index.ts
Labels: lgtm

#3711 fix(useCloned): correct return type
  packages/core/useCloned/index.ts
Labels: lgtm

#3687 feat(useBreakpoints): add `active` getter, add breakpoints for Vuetify v3
  packages/core/useBreakpoints/breakpoints.ts
  packages/core/useBreakpoints/demo.vue
  packages/core/useBreakpoints/index.md
  packages/core/useBreakpoints/index.ts
Labels: size:M, lgtm

#3650 fix(useCounter): allow `delta` to be negative
  packages/shared/useCounter/index.test.ts
  packages/shared/useCounter/index.ts
Labels: size:S, lgtm

#3552 feat(useTextareaAutosize): allow configuring `styleProp` to support native `rows` attribute
  packages/core/useTextareaAutosize/index.md
  packages/core/useTextareaAutosize/index.ts
Labels: size:M, lgtm

#3735 feat(useAxios): support `abortPrevious` option
  packages/integrations/useAxios/index.ts
Labels: size:S, lgtm

#3737 fix(useStorage): ensure setting value to null syncs to other instances
  packages/core/useStorage/index.test.ts
  packages/core/useStorage/index.ts
Labels: size:M, lgtm

#3793 feat(useEventSource): add `autoReconnect` and `immediate` to options, update typings
  packages/core/useEventSource/index.md
  packages/core/useEventSource/index.ts
Labels: size:L, lgtm

#3583 fix(useRouteParams,useRouteQuery): set route param/query to undefined when null or defaultValue
  packages/router/useRouteParams/index.test.ts
  packages/router/useRouteParams/index.ts
  packages/router/useRouteQuery/index.test.ts
  packages/router/useRouteQuery/index.ts
Labels: size:M, lgtm

#3605 fix(useScroll): add `onError` hook and avoid throws by default, fix #3580
  packages/core/useScroll/index.ts
Labels: size:M, lgtm

#3806 refactor(useStorage): minor cleanup
  packages/core/useStorage/index.ts
Labels: size:M, lgtm

#3802 fix(useMounted): compatible with vue2.7
  packages/core/useMounted/index.ts
Labels: size:XS, lgtm

#3805 fix(useIDBKeyval): use toRaw instead of overriding the original object
  packages/integrations/useIDBKeyval/index.ts
Labels: size:XS, lgtm

#3800 feat(whenever): override once option
  packages/shared/whenever/index.test.ts
  packages/shared/whenever/index.ts
Labels: size:M, lgtm

#3798 fix(useScrollLock): initialOverflow is not working
  packages/core/useScrollLock/index.test.ts
  packages/core/useScrollLock/index.ts
Labels: size:M, lgtm

#3815 fix(useActiveElement/useFocusWithin): replace computedWithControl with locally tracked ref
  packages/core/useActiveElement/index.ts
Labels: size:S, lgtm

#3812 fix(useClipboard): fix issue when permission is not defined
  packages/core/useClipboard/index.ts
Labels: size:XS, lgtm

#3829 docs(onLongPress): fix demo
  packages/core/onLongPress/index.md
Labels: size:XS
