Repository vueuse/vueuse, pull requests merged in 2024-08, with the labels that each got.

#4099 refactor(types): update `MaybeRef` types to match Vue3.5 and use local exports
  packages/core/useDropZone/index.ts
  packages/core/useEventSource/index.ts
  packages/integrations/useSortable/index.ts
  packages/shared/useCounter/index.ts
  packages/shared/utils/types.ts
Labels: need more info, size:M, lgtm

#4138 chore: typo
  packages/core/useFavicon/index.test.ts
Labels: size:S, lgtm

#4141 fix(isDefined): moves most specific overload to the top
  packages/shared/isDefined/index.ts
Labels: size:XS, lgtm

#4130 fix(useChangeCase): use the exported key for filter
  packages/integrations/useChangeCase/index.ts
Labels: size:XS, lgtm

#4113 fix(useRouteHash, useRouteParams, useRouteQuery): fix effect triggering multiple times
  packages/router/useRouteHash/index.test.ts
  packages/router/useRouteHash/index.ts
  packages/router/useRouteParams/index.test.ts
  packages/router/useRouteParams/index.ts
  packages/router/useRouteQuery/index.test.ts
  packages/router/useRouteQuery/index.ts
Labels: size:M, lgtm

#4132 fix(computedWithControl): allow optional oldValue parameter in computedWithControl getter
  packages/shared/computedWithControl/index.test.ts
  packages/shared/computedWithControl/index.ts
Labels: enhancement, size:S, lgtm

#4111 pref(createEventHook): optimize EventHookTrigger to support multiple parameters
  packages/shared/createEventHook/index.test.ts
  packages/shared/createEventHook/index.ts
Labels: enhancement, size:S

#4152 fix(useStorage): sync within the same document
  packages/core/useStorage/index.test.ts
  packages/core/useStorage/index.ts
Labels: bug, size:M, lgtm

#4157 fix(usePermission): fix memory leak
  packages/core/usePermission/index.ts
Labels: enhancement, size:S, lgtm

#4167 fix(usePermission): state setting
  packages/core/usePermission/index.ts
Labels: size:S, lgtm

#4168 fix(useDropZone): ensure files ref is updated even without onDrop callback
  packages/core/useDropZone/index.ts
Labels: size:S, lgtm

#4162 feat(templateRef): support specifying allowed keys via generic argument
  packages/core/templateRef/index.ts
Labels: enhancement, size:XS, lgtm

#4166 fix(useCssVar): Replace getComputedStyle with direct style property access
  packages/core/useCssVar/index.ts
Labels: size:XS, lgtm

#4151 fix(createSharedComposable): handle the case where the return value of composable function is empty
  packages/shared/createSharedComposable/index.ts
Labels: size:XS, lgtm

#4161 fix(useWebSocket): only reconnect if is the current ws socket
  packages/core/useWebSocket/index.ts
Labels: size:XS, lgtm

#4164 fix(useWebSocket): should reset retry count when connection is established
  packages/core/useWebSocket/index.ts
Labels: size:S, lgtm
