Repository vueuse/vueuse, pull requests merged in 2024-05, with the labels that each got.

#3964 chore: add vueuse open collective
  .github/FUNDING.yml
Labels: size:XS

#3983 docs: change composition api hyperlink
  packages/guide/index.md
Labels: size:XS

#3820 docs(useBreakpoints): list presets
  packages/core/useBreakpoints/index.md
Labels: size:S

#3968 Clarify code documentation in useIntervalFn
  packages/shared/useIntervalFn/index.ts
Labels: size:XS

#3975 feat(nuxt): Add router addon to nuxt module
  packages/nuxt/index.ts
Labels: size:XS

#3971 refactor(makeDestructurable): use const type parameters
  packages/shared/makeDestructurable/index.md
  packages/shared/makeDestructurable/index.ts
Labels: size:XS, lgtm

#3980 fix(useWebNotification): catch `TypeError`
  packages/core/useWebNotification/index.ts
Labels: size:S

#3984 feat(useEventSource): return `lastEventId`
  packages/core/useEventSource/index.ts
Labels: size:XS

#3966 refactor(useColorMode): Update demo.vue - better type
  packages/core/useColorMode/demo.vue
Labels: size:XS

#3932 docs(useGamepad): fix missing `.value` in example
  packages/core/useGamepad/index.md
Labels: size:XS

#3990 fix(useAnimate): `commitStyles` when finish
  packages/core/useAnimate/index.ts
Labels: size:XS, lgtm

#3940 fix(useElementSize): use getBoundingClientRect get element size on SVG
  packages/core/useElementSize/index.ts
Labels: size:XS, lgtm

#3908 docs: typo
  packages/core/useTimeoutPoll/index.md
Labels: size:XS

#3899 feat(useWebWorkerFn): support local function dependencies
  packages/core/useWebWorkerFn/index.md
  packages/core/useWebWorkerFn/index.ts
  packages/core/useWebWorkerFn/lib/createWorkerBlobUrl.ts
  packages/core/useWebWorkerFn/lib/depsParser.ts
Labels: size:M

#3902 feat(createInjectionState): add defaultValue option
  packages/shared/createInjectionState/index.md
  packages/shared/createInjectionState/index.ts
Labels: size:M, lgtm

#3870 fix(useWebSocket): urlRef changes were not being tracked
  packages/core/useWebSocket/index.ts
Labels: size:XS

#3934 feat(useRouteParams): support optional params
  packages/router/useRouteParams/index.test.ts
  packages/router/useRouteParams/index.ts
Labels: size:S

#3923 feat(useTimeout): target support reactivity
  packages/shared/useTimeout/index.test.ts
  packages/shared/useTimeout/index.ts
Labels: size:S

#3847 fix(useScrollLock): function unlock does not work
  packages/core/useScrollLock/index.ts
Labels: size:S

#3913 fix(useGamepad): avoid spread to fix gamepad state
  packages/core/useGamepad/index.ts
Labels: size:XS

#3972 fix(useFileDialog): check if input value exists before trigger onChange
  packages/core/useFileDialog/index.ts
Labels: size:XS

#3887 fix(useTextareaAutosize): onResize callback fires not only on resize
  packages/core/useTextareaAutosize/index.ts
Labels: size:XS

#3948 docs(refWithControl): typo
  packages/shared/refWithControl/index.ts
  packages/shared/useToNumber/index.ts
Labels: size:XS, lgtm

#3927 docs: adds default values to useThrottleFn notation
  packages/shared/useThrottleFn/index.ts
Labels: size:XS

#3921 fix(useMediaControls): target params may not be ref
  packages/core/useMediaControls/index.ts
Labels: size:XS, lgtm

#3976 fix(useDisplayMedia): stop stream when screen is not shared anymore
  packages/core/useDisplayMedia/index.ts
Labels: size:XS

#3817 fix(useScroll): sync scroll val to internal state #3809
  packages/core/useScroll/index.ts
Labels: size:XS

#3855 fix(useVirtualList): add containerRef to watch list
  packages/core/useVirtualList/index.ts
Labels: size:XS

#3791 feat(OnLongPress): `options.onMouseUp` callback
  packages/core/onLongPress/demo.vue
  packages/core/onLongPress/index.test.ts
  packages/core/onLongPress/index.ts
Labels: size:L, lgtm

#3958 feat(useActiveElement): add `triggerOnRemoval` option
  packages/core/useActiveElement/index.test.ts
  packages/core/useActiveElement/index.ts
Labels: size:M

#3995 types(vitest): modify `SpyInstance` to `MockInstance`
  packages/core/useEventListener/index.test.ts
  packages/core/useFetch/index.test.ts
Labels: size:S, lgtm

#3891 fix(useSpeechRecognition): send correct transcript result
  packages/core/useSpeechRecognition/index.ts
Labels: size:S, lgtm

#3994 feat(useFocus): support `preventScroll` option
  packages/core/useFocus/index.ts
Labels: size:S, lgtm
