Repository vueuse/vueuse, pull requests merged in 2024-11, with the labels that each got.

#4244 fix(useMouse): record the previous scroll value
  packages/core/useMouse/index.ts
Labels: size:S, lgtm

#4296 fix(useFetch): ensure single slash
  packages/core/useFetch/index.ts
Labels: size:XS, lgtm

#4340 fix(useUrlSearchParams): `hash` mode missing `location.search`
  packages/core/useUrlSearchParams/index.ts
Labels: size:XS, lgtm

#4283 fix(useRouteParams, useRouteQuery): effect triggers twice with object getter as watch source
  packages/router/useRouteParams/index.test.ts
  packages/router/useRouteParams/index.ts
  packages/router/useRouteQuery/index.test.ts
  packages/router/useRouteQuery/index.ts
Labels: size:M, lgtm

#4334 docs: add description to install vueuse using nuxi for nuxt
  packages/guide/index.md
  packages/nuxt/README.md
Labels: documentation, size:S, lgtm

#4330 Grammar in Docs
  packages/shared/refWithControl/index.md
Labels: documentation, size:XS

#4329 feat(useFetch): infer 'json' type for array payloads
  packages/core/useFetch/index.test.ts
  packages/core/useFetch/index.ts
Labels: size:S, lgtm

#4323 fix(useSwipe): allow vertical scrolling during swipe
  packages/core/useSwipe/index.ts
Labels: size:XS, lgtm

#4313 feat(OnClickOutside): support component with fragments
  packages/core/onClickOutside/index.ts
Labels: size:S, lgtm

#4332 fix(useSortable): wrong order of elements
  packages/integrations/useSortable/index.md
  packages/integrations/useSortable/index.ts
Labels: size:M, lgtm

#4333 docs(useIntersectionObserver): update syntax to handle stricter types
  packages/core/useIntersectionObserver/demo.vue
  packages/core/useIntersectionObserver/index.md
Labels: size:S

#4322 docs(useUserMedia): fix examples
  packages/core/useUserMedia/demo.vue
  packages/core/useUserMedia/index.md
Labels: size:XS, lgtm

#4326 feat(router): transform get / set
  packages/router/_types.ts
  packages/router/useRouteParams/index.test.ts
  packages/router/useRouteParams/index.ts
  packages/router/useRouteQuery/index.test.ts
  packages/router/useRouteQuery/index.ts
Labels: enhancement, size:M, lgtm

#4361 Documentation: Fix version typo for vue2
  README.md
  packages/guide/index.md
Labels: documentation, size:XS

#4359 docs(useUserMedia): fix demo.vue reactive import
  packages/core/useUserMedia/demo.vue
Labels: documentation, size:XS

#4363 docs: Update README.md
  README.md
Labels: documentation, size:XS

#4369 fix: typo on `watchWithFilter` docs
  packages/shared/watchWithFilter/index.md
Labels: documentation, size:XS
