Repository vueuse/vueuse, pull requests merged in 2024-09, with the labels that each got.

#4207 fix(computedAsync): type signature
  packages/core/computedAsync/index.test.ts
  packages/core/computedAsync/index.ts
Labels: size:S, lgtm

#4210 fix(useIntersectionObserver): add `Document` type for root
  packages/core/useIntersectionObserver/index.ts
Labels: size:XS, lgtm

#4199 docs(onKeyStroke): fix arrow down & up cause scroll event
  packages/core/onKeyStroke/demo.vue
Labels: size:XS, lgtm

#4189 fix(useMouseInElement): allow `el` to be instanceof Element
  packages/core/useMouseInElement/index.ts
Labels: size:XS, lgtm

#4211 fix(onClickOutside): make `ignore` accept reactive values
  packages/core/onClickOutside/index.ts
Labels: size:XS, lgtm

#4192 fix(useDraggable): draggable component not work with container
  packages/core/useDraggable/component.ts
Labels: size:XS, lgtm

#4134 fix(useFocusWithin): make useFocusWhithin match the behavior of the :focus-within
  packages/core/useFocusWithin/index.ts
Labels: size:S, lgtm

#4184 feat(useFileDialog): return `onCancel` handler
  packages/core/useFileDialog/demo.vue
  packages/core/useFileDialog/index.md
  packages/core/useFileDialog/index.ts
Labels: enhancement, size:S, lgtm

#4185 fix(onClickOutside): improve cross-browser compatibility
  packages/core/onClickOutside/index.ts
Labels: size:S

#4228 fix: typo in `useShare` docs
  packages/core/useShare/index.md
Labels: documentation, size:XS

#4218 fix(useResizeObserver): update type
  packages/core/useResizeObserver/index.ts
Labels: size:XS, lgtm

#4187 fix(useNetwork): return immutable values
  packages/core/useNetwork/index.ts
Labels: size:M, lgtm

#4227 feat(useDropZone): add multiple prop to control multi-file drop
  packages/core/useDropZone/index.md
  packages/core/useDropZone/index.ts
Labels: enhancement, size:L, lgtm

#4110 fix(useInfiniteScroll): stop watch when unmounted
  packages/core/useInfiniteScroll/index.ts
Labels: size:XS, lgtm

#4175 fix(useArrayFilter): match type to Array.prototype.filter
  packages/shared/useArrayFilter/index.test.ts
  packages/shared/useArrayFilter/index.ts
Labels: size:S, lgtm
