Repository vueuse/vueuse, pull requests merged in 2024-07, with the labels that each got.

#4096 docs: improve the team member layout style
  packages/.vitepress/theme/components/HomeTeam.vue
Labels: size:XS

#4079 docs(useCookies): Bump useCookies major version in docs
  packages/integrations/useCookies/index.md
Labels: size:XS

#4066 docs(@Motion): fix redirect @vueuse/motion cause 404
  meta/ecosystem-functions.ts
Labels: size:S, lgtm

#4068 fix(useGamepad): handle case where hapticActuators is not present
  packages/core/useGamepad/components/Gamepad.vue
Labels: size:XS, lgtm

#4055 fix(useWakeLock): should delay wake lock request if document is hidden
  packages/core/useWakeLock/index.md
  packages/core/useWakeLock/index.test.ts
  packages/core/useWakeLock/index.ts
Labels: size:L, lgtm

#4056 fix(useMouseInElement): el.getBoundingClientRect is not a function
  packages/core/useMouseInElement/index.ts
Labels: size:XS

#3821 feat(useCssVars): remove property on null/undefined
  packages/core/useCssVar/index.test.ts
  packages/core/useCssVar/index.ts
Labels: size:M, lgtm

#4005 fix(useResizeObserver): fix `target` is Ref Array
  packages/core/useResizeObserver/index.ts
Labels: size:S, lgtm

#4067 feat(useSpeechRecognition): support `maxAlternatives` option
  packages/core/useSpeechRecognition/index.ts
Labels: size:XS, lgtm

#4069 fix(useIntersectionObserver)!: update the `threshold` default to 0
  packages/core/useIntersectionObserver/index.ts
Labels: size:XS, lgtm

#4084 feat(useDraggable): add `buttons` option
  packages/core/useDraggable/component.ts
  packages/core/useDraggable/index.ts
Labels: size:S, lgtm

#4014 fix(useEventListener): event target can be an empty ref/getter
  packages/core/useEventListener/index.ts
Labels: size:XS, lgtm

#3822 feat(useStorage): conditionally use event based on the used storage backend
  packages/core/useStorage/index.ts
Labels: size:XS, lgtm

#4022 feat(useFocusTrap): support multiple refs
  packages/integrations/useFocusTrap/index.md
  packages/integrations/useFocusTrap/index.ts
Labels: direction: approved, size:M, lgtm

#4008 feat(useResizeObserver): added `vResizeObserver` directive
  packages/components/index.ts
  packages/core/useResizeObserver/directive.test.ts
  packages/core/useResizeObserver/directive.ts
  packages/core/useResizeObserver/index.md
Labels: size:L, lgtm

#3916 perf(useAnimate): set `sync` false
  packages/core/useAnimate/index.ts
Labels: size:XS, lgtm

#3907 feat(useDateFormat): locales is now reactive
  packages/shared/useDateFormat/demo.vue
  packages/shared/useDateFormat/index.ts
Labels: size:M, lgtm

#3892 feat(useInfiniteScroll): add a reset method
  packages/core/useInfiniteScroll/demo.vue
  packages/core/useInfiniteScroll/index.md
  packages/core/useInfiniteScroll/index.ts
Labels: size:S, lgtm

#4074 fix(useTextareaAutosize): improve `triggerResize` triggering
  packages/core/useTextareaAutosize/index.ts
Labels: size:S, lgtm

#4039 fix(until): cleanup at next tick to avoid memory leak
  packages/shared/until/index.ts
Labels: size:S, lgtm

#3950 feat(useWebSocket): allow different heartbeat response message
  packages/core/useWebSocket/index.ts
Labels: size:XS, lgtm

#3999 feat(useWindowSize): add ability to get outer sizes of the window
  packages/core/useWindowSize/index.test.ts
  packages/core/useWindowSize/index.ts
Labels: size:S, lgtm

#3869 feat(useElementBounding): add `updateTiming` option
  packages/core/useElementBounding/index.ts
Labels: size:S, lgtm
