Repository vueuse/vueuse, pull requests merged in 2024-06, with the labels that each got.

#4031 docs(useNProgress): fix dead link
  packages/integrations/useNProgress/index.md
Labels: size:XS

#4011 docs: update @vueuse/integrations link
  CONTRIBUTING.md
Labels: size:XS, lgtm

#4036 feat(useFuse)!: upgrade `fuse.js` to v7
  packages/integrations/package.json
  packages/integrations/useFuse/index.md
  packages/integrations/useFuse/index.ts
  pnpm-lock.yaml
Labels: BREAKING CHNAGE, size:S

#3510 feat(useJwt)!: upgrade `jwt-decode` to v4
  packages/integrations/package.json
  packages/integrations/useJwt/index.md
  packages/integrations/useJwt/index.test.ts
  packages/integrations/useJwt/index.ts
  pnpm-lock.yaml
Labels: BREAKING CHNAGE, size:S, lgtm

#4037 fix(useMutationObserver): stop watching before cleaning up
  packages/core/useMutationObserver/index.ts
Labels: size:XS, lgtm

#4060 docs: update API hyperlinks
  packages/core/createTemplatePromise/index.md
  packages/shared/toRefs/index.md
Labels: size:XS, lgtm

#4063 docs(useParentElement): fix demo not appearing in the docs
  packages/core/useParentElement/demo.vue
Labels: size:XS
