Repository vueuse/vueuse, pull requests merged in 2025-07, with the labels that each got.

#4781 feat(useIDBKeyval): add `options.serializer`
  packages/integrations/useIDBKeyval/index.test.ts
  packages/integrations/useIDBKeyval/index.ts
Labels: enhancement, size:L, lgtm

#4866 docs(useUrlSearchParams): enhance demo
  packages/core/useUrlSearchParams/demo.vue
Labels: documentation, size:XS, lgtm

#4856 docs: add responsive styles for input in small screens
  packages/.vitepress/theme/styles/demo.css
Labels: documentation, size:XS, lgtm

#4898 docs(refDebounce,refThrottled): add usage example with object ref
  packages/shared/refDebounced/index.md
  packages/shared/refThrottled/index.md
Labels: documentation, size:M, lgtm

#4904 docs(useSortable): moveArrayElement arguments
  packages/integrations/useSortable/index.md
Labels: documentation, size:XS, lgtm

#4901 docs(Elements): format the doc's Usage section
  packages/core/useActiveElement/index.md
  packages/core/useDocumentVisibility/index.md
  packages/core/useDropZone/index.md
  packages/core/useMutationObserver/index.md
  packages/core/useParentElement/index.md
  packages/core/useResizeObserver/index.md
  packages/core/useWindowFocus/index.md
  packages/core/useWindowScroll/index.md
  packages/core/useWindowSize/index.md
Labels: documentation, size:M, lgtm

#4913 fix(types): use Vue's native `MaybeRef` and `MaybeRefOrGetter` instead
  packages/core/useLocalStorage/index.ts
  packages/math/logicNot/index.ts
  packages/shared/get/index.ts
Labels: size:XS, lgtm

#4888 ci: add pkg.pr.new workflow
  .github/workflows/ci.yml
Labels: size:S, lgtm

#4915 docs(useAsyncState): fix usage example
  packages/core/useAsyncState/index.md
Labels: documentation, size:XS, lgtm

#4891 chore: update VSCode extensions recommendations
  .vscode/extensions.json
Labels: size:XS, lgtm

#4900 docs(useElementBounding,useElementSize): convert `<script>` to `<script setup lang="ts">`
  packages/core/useElementBounding/index.md
  packages/core/useElementSize/index.md
Labels: documentation, size:M, lgtm

#4849 feat(useFocusTrap): expose updateContainerElements for dynamic contai…
  packages/integrations/useFocusTrap/index.md
  packages/integrations/useFocusTrap/index.ts
Labels: enhancement, size:M, lgtm

#4884 docs: inline Key components in useMagicKeys and useKeyModifier demos
  packages/core/useKeyModifier/demo.vue
  packages/core/useMagicKeys/Key.vue
  packages/core/useMagicKeys/demo.vue
Labels: documentation, size:M, lgtm

#4916 fix(useMagicKeys): prevent incorrect clearing of other keys after releasing shift
  packages/core/useMagicKeys/index.test.ts
  packages/core/useMagicKeys/index.ts
Labels: size:M, lgtm

#4893 refactor(integrations): use direct imports in demos
  packages/integrations/useAsyncValidator/demo.client.vue
  packages/integrations/useAxios/demo.vue
  packages/integrations/useChangeCase/demo.vue
  packages/integrations/useDrauu/demo.client.vue
  packages/integrations/useFocusTrap/demo.vue
  packages/integrations/useFuse/demo.vue
  packages/integrations/useIDBKeyval/demo.client.vue
  packages/integrations/useJwt/demo.vue
  packages/integrations/useNProgress/demo.vue
  packages/integrations/useQRCode/demo.vue
  packages/integrations/useSortable/demo.vue
Labels: size:S, lgtm

#4878 chore: add new script for updating dependencies and checking size
  package.json
Labels: dependencies, size:XS

#4839 fix(onClickOutside): the order of overload signatures
  packages/core/onClickOutside/index.ts
Labels: size:M, lgtm

#4158 feat(useStorageAsync): add `onReady` option and Promise return
  packages/core/useStorageAsync/index.md
  packages/core/useStorageAsync/index.test.ts
  packages/core/useStorageAsync/index.ts
Labels: size:L, lgtm

#4813 feat(useFileDialog): add MaybRef to multiple, accept, capture, reset, and directory
  packages/core/useFileDialog/index.test.ts
  packages/core/useFileDialog/index.ts
Labels: enhancement, size:L, lgtm

#4850 feat(useTransition): support custom window
  packages/core/useTransition/index.ts
Labels: enhancement, size:XS, lgtm

#4853 refactor(test): add MSW mock server to setup
  packages/.test/setup.ts
  packages/core/useFetch/index.test.ts
Labels: size:XS, lgtm

#4919 types: add `@vueuse/integrations/*` paths
  tsconfig.json
Labels: size:XS

#4925 fix(ci): avoid duplicate `nr update` execution in `docs:build`
  package.json
Labels: build tools, size:XS

#4932 docs: add `whitelistCommits` for Changelog
  scripts/changelog.ts
Labels: documentation, size:XS

#4931 feat(computedAsync): add demo
  packages/core/computedAsync/demo.vue
Labels: documentation, size:M, lgtm
