Repository vueuse/vueuse, pull requests merged in 2025-06, with the labels that each got.

#4789 fix(useScreenSafeArea): сhanged initial value update
  packages/core/useScreenSafeArea/index.ts
Labels: size:XS, lgtm

#4471 feat(useRefHistory): add `shouldCommit`
  packages/core/useRefHistory/index.test.ts
  packages/core/useRefHistory/index.ts
Labels: enhancement, size:M, lgtm

#4809 fix(watchIgnorable): add and export types
  packages/shared/watchIgnorable/index.ts
Labels: size:XS, lgtm

#4823 docs(useElementVisibility): explain threshold option
  packages/core/useElementVisibility/index.md
Labels: documentation, size:S, lgtm

#4716 feat(useAsyncState): add executeImmediate with the same type as the promise fn
  packages/core/useAsyncState/index.md
  packages/core/useAsyncState/index.test.ts
  packages/core/useAsyncState/index.ts
Labels: enhancement, size:M, lgtm

#4801 feat(shared): Introduce `TimerHandle` for setTimeout type
  packages/core/onLongPress/index.ts
  packages/core/useElementHover/index.ts
  packages/core/useIdle/index.ts
  packages/core/useWebSocket/index.ts
  packages/shared/refAutoReset/index.ts
  packages/shared/useTimeoutFn/index.ts
  packages/shared/utils/filters.ts
  packages/shared/utils/types.ts
Labels: enhancement, size:M, lgtm

#4787 fix(useEventListener): improve types
  packages/core/useEventListener/index.test.ts
  packages/core/useEventListener/index.ts
Labels: size:M, lgtm

#4820 feat(useFetch): support for custom abort reason
  packages/core/useFetch/index.test.ts
  packages/core/useFetch/index.ts
Labels: enhancement, size:S, lgtm

#4791 feat(useEventSource): added lastEventId for named events
  packages/core/useEventSource/index.ts
Labels: enhancement, size:XS, lgtm

#4826 perf(computedWithControl): Optimize with shallowRef
  packages/shared/computedWithControl/index.ts
Labels: size:S, lgtm

#4786 fix(computedWithControl): allow deeply watching source
  packages/shared/computedWithControl/index.md
  packages/shared/computedWithControl/index.test.ts
  packages/shared/computedWithControl/index.ts
Labels: size:M, lgtm

#4433 fix(useScroll): use mutationObserver to update arrivedState when the DOM is changed
  packages/core/useScroll/index.browser.test.ts
  packages/core/useScroll/index.ts
Labels: needs test, size:L, lgtm

#4773 feat(useUrlSearchParams): Add a stringify option for users to provide stringify logic
  packages/core/useUrlSearchParams/index.md
  packages/core/useUrlSearchParams/index.test.ts
  packages/core/useUrlSearchParams/index.ts
Labels: enhancement, size:M, lgtm

#4829 refactor(computedInject): rename ctx param to oldValue
  packages/core/computedInject/index.test.ts
  packages/core/computedInject/index.ts
Labels: size:S, lgtm

#4830 fix: render Comp to trigger its setup
  packages/.test/mount.ts
Labels: size:XS, lgtm

#4837 feat(useSpeechSynthesis): add reactivity for volume
  packages/core/useSpeechSynthesis/demo.vue
  packages/core/useSpeechSynthesis/index.ts
Labels: enhancement, size:S, lgtm

#4836 docs: onClickOutside ignore by CSS Selectors
  packages/core/onClickOutside/index.md
  packages/core/onClickOutside/index.ts
Labels: documentation, size:S, lgtm

#4834 fix(useCookie): update `universal-cookie` range to `^7 || ^8`
  packages/integrations/package.json
Labels: dependencies, size:XS, lgtm
