Repository vueuse/vueuse, pull requests merged in 2025-01, with the labels that each got.

#4448 test(useElementBounding): add basic browser tests
  packages/core/useElementBounding/index.browser.test.ts
  packages/core/useElementBounding/index.test.ts
  tsconfig.json
  vitest.workspace.ts
Labels: size:L, lgtm, test suites

#4232 fix(useTimeoutPoll): `immediate` default value should be `true`
  packages/core/useTimeoutPoll/index.ts
Labels: size:S, lgtm

#4432 feat(toArray): new utility function
  packages/core/useElementSize/index.ts
  packages/core/useEventListener/index.ts
  packages/core/useIntersectionObserver/index.ts
  packages/core/useMutationObserver/index.ts
  packages/integrations/useFocusTrap/index.ts
  packages/shared/syncRefs/index.ts
  packages/shared/utils/index.ts
Labels: enhancement, new function, size:M, lgtm

#4439 docs(useInfiniteScroll): add warning and examples for `canLoadMore`
  packages/core/useInfiniteScroll/demo.vue
  packages/core/useInfiniteScroll/index.md
Labels: documentation, size:S, lgtm

#4436 feat(useElementBounding): added directive for `vElementBounding`
  packages/components/index.ts
  packages/core/useElementBounding/directive.test.ts
  packages/core/useElementBounding/directive.ts
  packages/core/useElementBounding/index.md
Labels: directive, size:L, lgtm

#4426 feat(router): support partial transform
  packages/router/_types.ts
  packages/router/useRouteParams/index.test.ts
  packages/router/useRouteParams/index.ts
  packages/router/useRouteQuery/index.test.ts
  packages/router/useRouteQuery/index.ts
Labels: enhancement, size:L, lgtm

#4410 feat(onElementRemoval): new function, refactor `useActiveElement` `useElementHover`
  packages/core/index.ts
  packages/core/onElementRemoval/demo.vue
  packages/core/onElementRemoval/index.md
  packages/core/onElementRemoval/index.test.ts
  packages/core/onElementRemoval/index.ts
  packages/core/useActiveElement/index.ts
  packages/core/useElementHover/index.ts
Labels: size:L, lgtm

#4438 feat(useMouseInElement): added directive for `vMouseInElement`
  packages/components/index.ts
  packages/core/useMouseInElement/directive.test.ts
  packages/core/useMouseInElement/directive.ts
  packages/core/useMouseInElement/index.md
Labels: directive, size:L, lgtm

#4452 fix(useStorageAsync): correct initialization when `initialValue` is getter
  packages/core/useStorageAsync/index.ts
Labels: size:XS, lgtm

#4441 feat(useToNumber): `method` support custom function
  packages/shared/useToNumber/index.test.ts
  packages/shared/useToNumber/index.ts
Labels: size:S, lgtm

#4458 test: use `vue-tsc` instead of `tsc` to also check `*.vue` files
  package.json
  packages/.vitepress/theme/components/Changelog.vue
  packages/core/useAsyncState/demo.vue
  packages/core/useAsyncState/index.ts
  packages/core/useCssVar/index.ts
  packages/core/useFetch/demo.vue
  packages/core/useGamepad/components/Gamepad.vue
  packages/core/useMouse/demo.vue
  packages/core/useParallax/demo.vue
  packages/core/usePointerLock/demo.vue
  packages/integrations/useNProgress/index.ts
  packages/shared/useDateFormat/demo.vue
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
Labels: build tools, size:M

#4470 feat(useCloned): return `isModified`
  packages/core/useCloned/index.md
  packages/core/useCloned/index.test.ts
  packages/core/useCloned/index.ts
Labels: enhancement, size:M, lgtm

#4467 docs(useMediaControls): use useTemplateRef instead of ref
  packages/core/useMediaControls/index.md
Labels: documentation, size:XS, lgtm

#4477 feat: use passive event handlers everywhere is possible
  packages/core/onClickOutside/index.ts
  packages/core/useActiveElement/index.ts
  packages/core/useClipboard/index.ts
  packages/core/useClipboardItems/index.ts
  packages/core/useDeviceMotion/index.ts
  packages/core/useDeviceOrientation/index.ts
  packages/core/useDevicesList/index.ts
  packages/core/useDocumentVisibility/index.ts
  packages/core/useDraggable/index.ts
  packages/core/useFocus/index.ts
  packages/core/useFocusWithin/index.ts
  packages/core/useFullscreen/index.ts
  packages/core/useGamepad/index.ts
  packages/core/useIdle/index.ts
  packages/core/useMagicKeys/index.ts
  packages/core/useMediaControls/components/Menu.vue
  packages/core/useMediaControls/components/Scrubber.vue
  packages/core/useMediaControls/index.ts
  packages/core/useMouse/index.ts
  packages/core/useMouseInElement/index.ts
  packages/core/useMousePressed/index.ts
  packages/core/useNavigatorLanguage/index.ts
  packages/core/useNetwork/index.ts
  packages/core/usePageLeave/index.ts
  packages/core/usePermission/index.ts
  packages/core/usePointerLock/index.ts
  packages/core/usePointerSwipe/index.ts
  packages/core/usePreferredLanguages/index.ts
  packages/core/useScreenOrientation/index.ts
  packages/core/useScreenSafeArea/index.ts
  packages/core/useStorage/index.ts
  packages/core/useStorageAsync/index.ts
  packages/core/useSwipe/index.ts
  packages/core/useTextSelection/index.ts
  packages/core/useUrlSearchParams/index.ts
  packages/core/useWakeLock/index.ts
  packages/core/useWebSocket/index.ts
  packages/core/useWindowFocus/index.ts
  packages/core/useWindowSize/index.ts
Labels: size:L, lgtm

#4464 feat(useStorage): make storage key reactive
  packages/core/useLocalStorage/index.ts
  packages/core/useSessionStorage/index.ts
  packages/core/useStorage/index.md
  packages/core/useStorage/index.test.ts
  packages/core/useStorage/index.ts
Labels: enhancement, size:L, lgtm

#4460 fix(useBluetooth): isConnected state not changed when disconnected
  packages/core/useBluetooth/index.ts
Labels: size:S, lgtm

#4428 docs: fix linking to category filter
  packages/.vitepress/theme/components/FunctionsList.vue
Labels: documentation, size:M

#4481 refactor(useDevicePixelRatio): use `useMediaQuery`
  packages/core/useDevicePixelRatio/index.ts
Labels: size:S, lgtm

#4486 feat(useEventListener): make all parameters arrayable and reactive
  packages/core/useEventListener/index.test.ts
  packages/core/useEventListener/index.ts
Labels: enhancement, size:L, lgtm

#4479 feat: use `useEventListener` where it was not being used
  packages/core/onClickOutside/index.ts
  packages/core/useBluetooth/index.md
  packages/core/useBluetooth/index.ts
  packages/core/useBroadcastChannel/index.ts
  packages/core/useDisplayMedia/index.ts
  packages/core/useMediaControls/index.ts
  packages/core/useMediaQuery/index.ts
  packages/core/useScriptTag/index.ts
  packages/guidelines.md
  packages/shared/useDebounceFn/index.md
  packages/shared/useThrottleFn/index.md
Labels: size:L, lgtm

#4485 test(useCookies): add unit test
  packages/integrations/useCookies/index.test.ts
Labels: size:M, lgtm, test suites

#4498 ci: add node version `22.x` to test matrix
  .github/workflows/ci.yml
Labels: size:XS, lgtm

#4511 docs(useTitle): update tip for auto import in Nuxt 3
  packages/core/useTitle/index.md
  packages/core/useTitle/index.ts
  packages/nuxt/index.ts
Labels: documentation, size:XS, lgtm

#4502 test(core): suppress some output in test runs
  packages/integrations/useAsyncValidator/index.test.ts
  packages/rxjs/watchExtractedObservable/index.test.ts
  packages/shared/utils/index.test.ts
Labels: size:S, lgtm

#4520 docs: update VitePress to 1.6.1
  packages/.vitepress/theme/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies, size:S, lgtm

#4501 chore(deps): update to vitest@3
  package.json
  packages/core/useFetch/index.test.ts
  packages/core/useRafFn/index.test.ts
  packages/core/useScriptTag/index.test.ts
  packages/core/useStorage/index.test.ts
  packages/core/useWebSocket/index.test.ts
  packages/core/useWindowSize/index.test.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  vitest.config.ts
  vitest.workspace.ts
Labels: dependencies, size:L, lgtm

#4482 refactor: use `useTemplateRef` instead of `ref` in demos and docs
  packages/core/useAnimate/demo.vue
  packages/core/useAnimate/index.md
  packages/core/useCssVar/demo.vue
  packages/core/useCssVar/index.md
  packages/core/useDraggable/demo.vue
  packages/core/useDraggable/index.md
  packages/core/useElementBounding/demo.vue
  packages/core/useElementBounding/index.md
  packages/core/useElementHover/demo.vue
  packages/core/useElementSize/demo.vue
  packages/core/useElementSize/index.md
  packages/core/useElementVisibility/demo.vue
  packages/core/useEventListener/index.md
  packages/core/useFullscreen/demo.vue
  packages/core/useFullscreen/index.md
  packages/core/useInfiniteScroll/demo.vue
  packages/core/useInfiniteScroll/index.md
  packages/core/useMousePressed/demo.vue
  packages/core/useMousePressed/index.md
  packages/core/useMutationObserver/index.md
  packages/core/usePointerSwipe/index.md
  packages/core/useResizeObserver/demo.vue
  packages/core/useResizeObserver/index.md
  packages/core/useScroll/demo.vue
  packages/core/useScroll/index.md
  packages/core/useScrollLock/demo.vue
  packages/core/useScrollLock/index.md
  packages/core/useSwipe/index.md
  packages/guide/components.md
  packages/integrations/useSortable/demo.vue
  packages/integrations/useSortable/index.md
Labels: documentation, size:L, lgtm

#4509 feat(useFileDialog): add initialFiles option
  packages/core/useFileDialog/index.test.ts
  packages/core/useFileDialog/index.ts
Labels: enhancement, size:M, lgtm

#4505 fix(useMagicKeys): fix key order issue on first use
  packages/core/useMagicKeys/index.test.ts
  packages/core/useMagicKeys/index.ts
Labels: size:M, lgtm

#4497 fix(debounceFilter): invoke on maxWait with the latest invoker
  packages/shared/utils/filters.ts
  packages/shared/watchDebounced/index.test.ts
Labels: size:M, lgtm

#4125 feat(useCountdown): new function
  packages/core/useCountdown/demo.vue
  packages/core/useCountdown/index.md
  packages/core/useCountdown/index.test.ts
  packages/core/useCountdown/index.ts
Labels: new function, size:L, lgtm

#4504 fix(useVirtualList): allow readonly arrays as input
  packages/core/useVirtualList/index.test.ts
  packages/core/useVirtualList/index.ts
Labels: size:S, lgtm

#4512 feat(useClipboard): should fall back to legacy clipboard when read/write fails
  packages/core/useClipboard/index.browser.test.ts
  packages/core/useClipboard/index.test.ts
  packages/core/useClipboard/index.ts
Labels: enhancement, size:M, lgtm

#4513 docs(useClipboardItems): fix demo by using `text/plain` mime type
  packages/core/useClipboardItems/demo.vue
  packages/core/useClipboardItems/index.md
Labels: documentation, size:S, lgtm

#4499 feat(useFetch): add parameters to the `afterFetch` and `onFetchError`
  packages/core/useFetch/index.md
  packages/core/useFetch/index.test.ts
  packages/core/useFetch/index.ts
Labels: enhancement, size:L, lgtm

#4526 docs: update VitePress to 1.6.3 (search broken)
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies, size:XS, lgtm

#4536 chore: upgrade playwright
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies, size:XS, lgtm

#4540 chore: use local playwright
  .github/workflows/ci.yml
Labels: size:XS, lgtm

#4535 feat(createReusableTemplate): explicit props
  packages/core/createReusableTemplate/index.md
  packages/core/createReusableTemplate/index.ts
Labels: enhancement, size:M, lgtm

#4541 refactor(useFullscreen): use documentElement directly
  packages/core/useFullscreen/index.ts
Labels: size:XS, lgtm

#4528 fix(reactiveComputed): computed fn should be `ComputedGetter`
  packages/shared/reactiveComputed/index.test.ts
  packages/shared/reactiveComputed/index.ts
Labels: size:S, lgtm

#4525 chore: update issue templates to support githubs new issue types
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size:S, lgtm

#4524 test(useCountdown): replace `promiseTimeout` with `advanceTimersByTime`
  packages/core/useCountdown/index.test.ts
Labels: size:S, lgtm

#4549 docs(useElementVisibility): Fix rootMargin docs
  packages/core/useElementVisibility/index.md
Labels: documentation, size:XS, lgtm

#4552 chore: downgrade playwright to prevent flaky FF tests
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies, size:XS, lgtm
