Repository vueuse/vueuse, pull requests merged in 2025-03, with the labels that each got.

#4616 fix(onStartTyping): Incorrect accepted valid characters
  packages/core/onStartTyping/index.test.ts
  packages/core/onStartTyping/index.ts
Labels: size:M, lgtm

#4598 refactor(useEventSource): use `shallowRef` for event & allow any data
  packages/core/useEventSource/index.ts
Labels: size:M, lgtm

#4602 test(useEventSource): add initial tests
  packages/core/useEventSource/index.test.ts
Labels: size:L, lgtm

#4638 docs: set right the links
  packages/core/createReusableTemplate/index.md
  packages/core/useDeviceMotion/index.md
  packages/core/useDeviceOrientation/index.md
  packages/integrations/useFocusTrap/index.md
Labels: documentation, size:XS, lgtm

#4608 fix(useWebSocket): don't call close() on pongTimeout if connection al…
  packages/core/useWebSocket/index.test.ts
  packages/core/useWebSocket/index.ts
Labels: size:L, lgtm

#4559 fix(useDeviceList): audioInputs doesn't update if camera permission is `granted`
  packages/core/useDevicesList/index.ts
Labels: size:XS, lgtm

#4645 fix(useEventSource): remove readonly to not be breaking
  packages/core/useEventSource/index.ts
Labels: size:S

#4648 test(ci): add additional attw test for built packages
  .github/workflows/ci.yml
  attw-esm-only.json
  package.json
  packages/components/package.json
  packages/core/package.json
  packages/electron/package.json
  packages/firebase/package.json
  packages/integrations/package.json
  packages/math/package.json
  packages/metadata/package.json
  packages/nuxt/package.json
  packages/router/package.json
  packages/rxjs/package.json
  packages/shared/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size:M, lgtm

#4581 feat!: drop CJS build, now it's ESM-only
  .attw.json
  .gitignore
  attw-esm-only.json
  meta/packages.ts
  package.json
  packages/.vitepress/vite.config.ts
  packages/components/package.json
  packages/core/metadata.cjs
  packages/core/metadata.d.cts
  packages/core/metadata.d.ts
  packages/core/package.json
  packages/electron/package.json
  packages/firebase/package.json
  packages/integrations/package.json
  packages/math/package.json
  packages/metadata/package.json
  packages/metadata/types.ts
  packages/nuxt/package.json
  packages/router/package.json
  packages/rxjs/package.json
  packages/shared/package.json
  packages/shared/toRef/index.ts
  packages/shared/utils/general.ts
  packages/shared/utils/index.test.ts
  packages/shared/utils/index.ts
  packages/shared/utils/vue.ts
  rollup.config.ts
  scripts/utils.ts
Labels: BREAKING CHNAGE, dependencies, size:XL, lgtm

#4660 docs(useWebNotification): add permission tip and update example
  packages/core/useWebNotification/index.md
Labels: documentation, size:XS, lgtm

#4663 fix(docs): blog moved to different domain
  packages/shared/refDebounced/index.md
  packages/shared/refThrottled/index.md
  packages/shared/useDebounceFn/index.md
  packages/shared/useThrottleFn/index.md
Labels: documentation, size:XS, lgtm

#4675 docs(refAutoReset): add info about using `triggerRef` for deep mutations
  packages/shared/refAutoReset/index.md
Labels: documentation, size:XS, lgtm

#4673 docs(changelog): fix date hydration mismatch
  packages/.vitepress/theme/components/Changelog.vue
  packages/.vitepress/theme/components/ChangelogEntry.vue
Labels: documentation, size:L, lgtm

#4650 chore: switch to yaml for tests
  package.json
  packages/.vitepress/plugins/utils.ts
  packages/.vitepress/vite.config.ts
  packages/core/useAsyncState/demo.vue
  packages/core/useMediaQuery/demo.vue
  packages/core/useParallax/demo.vue
  packages/core/usePermission/demo.vue
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/utils.ts
  test/exports.test.ts
Labels: dependencies, size:M, lgtm
