Repository vueuse/vueuse, pull requests merged in 2025-02, with the labels that each got.

#4555 fix(createEventHook): type check for multiple arguments
  packages/shared/createEventHook/index.ts
Labels: size:XS, lgtm

#4565 fix(useSpeechRecognition): improve start and stop method behavior
  packages/core/useSpeechRecognition/index.ts
Labels: size:S, lgtm

#4527 test(onClickOutside): browser tests for ignored elements
  packages/core/onClickOutside/index.browser.test.ts
Labels: size:M, test suites

#4533 feat(watchPausable): add `options.initialState` to control the initial active value
  packages/shared/utils/filters.ts
  packages/shared/utils/index.test.ts
  packages/shared/watchPausable/index.test.ts
  packages/shared/watchPausable/index.ts
Labels: enhancement, size:L, lgtm

#4571 fix(nuxt): check if packages exist in any layer
  packages/nuxt/index.ts
Labels: size:XS, lgtm

#4531 chore(deps): update vitest to 3.0.4 to fix coverage with multiple browser instances
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  vitest.config.ts
Labels: dependencies, size:S, lgtm

#4572 docs: preserve character after function names when linkifying
  packages/.vitepress/plugins/markdownTransform.ts
Labels: size:XS, lgtm

#4537 feat(onClickOutside): add `controls`
  packages/core/onClickOutside/component.ts
  packages/core/onClickOutside/directive.ts
  packages/core/onClickOutside/index.md
  packages/core/onClickOutside/index.ts
Labels: enhancement, size:M, lgtm

#4500 fix(useCssVar): new Behavior
  packages/core/useCssVar/index.test.ts
  packages/core/useCssVar/index.ts
Labels: size:L, lgtm

#4457 fix(useMouse): check for `MouseEvent` instead of `Touch` to work with FF
  package.json
  packages/core/useMouse/demo.browser.test.ts
  packages/core/useMouse/demo.vue
  packages/core/useMouse/index.md
  packages/core/useMouse/index.ts
  packages/core/usePointerLock/demo.browser.test.ts
  packages/core/usePointerLock/index.ts
  vitest.config.ts
Labels: size:M, lgtm

#4553 feat(useDateFormat): add `z...zzzz` for timezone information
  packages/shared/useDateFormat/index.md
  packages/shared/useDateFormat/index.test.ts
  packages/shared/useDateFormat/index.ts
  vitest.config.ts
Labels: enhancement, size:M, lgtm

#4579 fix(useAnimate): Clear animate when element is gone
  packages/core/useAnimate/index.ts
Labels: size:XS, lgtm

#4577 feat(useElementVisibility): add `once` options
  packages/core/useElementVisibility/index.test.ts
  packages/core/useElementVisibility/index.ts
Labels: enhancement, size:S, lgtm

#4583 feat(useRafFn): add `once` option
  packages/core/useRafFn/index.test.ts
  packages/core/useRafFn/index.ts
Labels: enhancement, size:S, lgtm

#4584 refactor: replace `tryOnBeforeUnmount` with `tryOnScopeDispose`
  packages/core/useTitle/index.ts
Labels: size:XS, lgtm

#4557 fix(useTextareaAutosize): improve resize handling with requestAnimationFrame
  packages/core/useTextareaAutosize/index.ts
Labels: size:M, lgtm

#4430 fix(useFetch): partial overwrite when `{combination: 'overwrite'}`
  packages/core/useFetch/index.test.ts
  packages/core/useFetch/index.ts
Labels: needs test, size:M, lgtm

#4592 refactor: move to `shallowRef` in shared utilities
  packages/shared/createInjectionState/index.test.ts
  packages/shared/isDefined/index.test.ts
  packages/shared/reactify/index.test.ts
  packages/shared/syncRef/index.test.ts
  packages/shared/until/index.test.ts
  packages/shared/useLastChanged/index.ts
  packages/shared/watchTriggerable/index.test.ts
  packages/shared/whenever/index.test.ts
Labels: size:M, lgtm

#4594 refactor(useDocumentVisibility): use `shallowRef` for primitives
  packages/core/useDocumentVisibility/index.ts
Labels: size:XS, lgtm

#4593 refactor(useCloned): use `shallowRef` for primitives
  packages/core/useCloned/index.ts
Labels: size:XS, lgtm

#4597 refactor(useFetch): use `shallowRef` for status codes
  packages/core/useFetch/index.ts
Labels: size:XS

#4595 refactor(useElementSize): use `shallowRef` for height and width
  packages/core/useElementSize/index.ts
Labels: size:XS

#4596 docs: update README.md usage example to script setup
  README.md
Labels: documentation, size:M

#4589 test: temp disable flaky firefox browser instance
  pnpm-lock.yaml
  pnpm-workspace.yaml
  vitest.config.ts
Labels: size:XS, lgtm

#4606 chore: remove 'experimental' from 'eslint.experimental.useFlatConfig' in VSCode settings
  .vscode/settings.json
Labels: size:XS, lgtm

#4591 feat(useCached): add `options.deepRefs`
  packages/core/_configurable.ts
  packages/core/useCached/index.test.ts
  packages/core/useCached/index.ts
  packages/core/useSupported/index.ts
  packages/shared/createRef/index.md
  packages/shared/createRef/index.test.ts
  packages/shared/createRef/index.ts
  packages/shared/index.ts
Labels: enhancement, size:L, lgtm

#4619 fix(useAnimate): Correct condition for updating keyframes
  packages/core/useAnimate/index.ts
Labels: size:S, lgtm

#4624 chore: typo
  rollup.config.ts
Labels: size:XS, lgtm

#4622 test(useAnimate): add test for keyframe reactivity
  packages/core/useAnimate/index.browser.test.ts
Labels: size:M, lgtm

#4626 chore: upgrade vitest to 3.0.7
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies, size:S, lgtm

#4615 fix(useClipboard): unhandled rejection on read permission prompt
  packages/core/useClipboard/index.ts
Labels: size:XS, lgtm
