Repository vueuse/vueuse, pull requests merged in 2025-04, with the labels that each got.

#4651 refactor: Loosen UseTextareAutosizeOptions['element'] type to be `| undefined | null`
  packages/core/useTextareaAutosize/index.ts
Labels: size:XS, lgtm

#4681 fix(useDropZone): Allow passing `document` as target
  packages/core/useDropZone/index.ts
Labels: size:XS, lgtm

#4687 test: fix types of some mount calls
  packages/core/useAnimate/index.browser.test.ts
  packages/core/useAnimate/index.test.ts
  packages/core/useCurrentElement/index.test.ts
Labels: size:M, lgtm

#4696 chore: typo
  packages/core/createTemplatePromise/index.md
Labels: documentation, size:XS

#4698 fix(nuxt): don't require `@vueuse/core` installed at root
  packages/nuxt/index.ts
Labels: size:XS, lgtm

#4692 docs: add responsive styles for textarea in small screens
  packages/.vitepress/theme/styles/demo.css
Labels: size:XS, lgtm

#4684 feat(useSortable): Add possibility to use it with Component ref
  packages/integrations/useSortable/index.browser.test.ts
  packages/integrations/useSortable/index.ts
Labels: enhancement, size:M, lgtm

#4685 fix(tryOnMounted): pass target to getLifeCycleTarget
  packages/shared/tryOnMounted/index.ts
Labels: size:XS, lgtm

#4659 feat(shared): ensure return types exists
  packages/shared/computedEager/index.ts
  packages/shared/computedWithControl/index.ts
  packages/shared/createEventHook/index.ts
  packages/shared/createGlobalState/index.ts
  packages/shared/createRef/index.ts
  packages/shared/createSharedComposable/index.ts
  packages/shared/extendRef/index.ts
  packages/shared/get/index.ts
  packages/shared/isDefined/index.ts
  packages/shared/provideLocal/index.ts
  packages/shared/reactify/index.ts
  packages/shared/reactifyObject/index.ts
  packages/shared/reactiveComputed/index.ts
  packages/shared/reactiveOmit/index.ts
  packages/shared/reactivePick/index.ts
  packages/shared/refAutoReset/index.ts
  packages/shared/refDebounced/index.ts
  packages/shared/refThrottled/index.ts
  packages/shared/toRefs/index.ts
  packages/shared/useArrayDifference/index.ts
  packages/shared/useArrayEvery/index.ts
  packages/shared/useArrayFilter/index.ts
  packages/shared/useArrayFind/index.ts
  packages/shared/useArrayFindIndex/index.ts
  packages/shared/useArrayFindLast/index.ts
  packages/shared/useArrayIncludes/index.ts
  packages/shared/useArrayJoin/index.ts
  packages/shared/useArrayMap/index.ts
  packages/shared/useArraySome/index.ts
  packages/shared/useArrayUnique/index.ts
  packages/shared/useCounter/index.ts
  packages/shared/useDateFormat/index.ts
  packages/shared/useDebounceFn/index.ts
  packages/shared/useInterval/index.ts
  packages/shared/useIntervalFn/index.ts
  packages/shared/useLastChanged/index.ts
  packages/shared/useTimeout/index.ts
  packages/shared/useTimeoutFn/index.ts
  packages/shared/useToggle/index.ts
  packages/shared/utils/types.ts
Labels: enhancement, size:L, lgtm

#4706 chore: recommend opening a reproduction via playground.vueuse.org
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: size:XS

#4715 fix(UseArrayFindReturn): Missing template type
  packages/shared/useArrayFind/index.ts
Labels: size:XS, lgtm

#4720 fix: allow vertical scroll in usePointerSwipe (#4637)
  packages/core/usePointerSwipe/index.ts
Labels: size:XS, lgtm

#4722 fix(useElementSize): component type warning
  packages/core/useElementSize/component.ts
Labels: size:XS, lgtm

#4730 fix: always mount listeners in useStorage
  packages/core/useStorage/index.ts
Labels: size:M, lgtm
