Repository vueuse/vueuse, pull requests merged in 2025-05, with the labels that each got.

#4726 fix(useEventSource): add missing data generic
  packages/core/useEventSource/index.ts
Labels: size:XS, lgtm

#4735 fix(onClickOutside): workaround for iOS
  packages/core/onClickOutside/index.ts
Labels: size:XS, lgtm

#4736 docs: remove vue 3 only warnings
  packages/core/createTemplatePromise/index.md
  packages/core/useCurrentElement/index.md
  packages/core/useCurrentElement/index.test.ts
  packages/core/useTemplateRefsList/index.md
  packages/index.md
  packages/router/README.md
  packages/shared/refWithControl/index.md
Labels: documentation, size:S, lgtm

#4738 docs(pausableWatch): suggest to use Vue's native since 3.5
  packages/shared/watchPausable/index.md
Labels: documentation, size:XS, lgtm

#4743 docs(watchOnce): suggest to use Vue's native feature since 3.4
  packages/shared/watchOnce/index.md
Labels: documentation, size:XS, lgtm

#4746 feat(computedAsync): add option to control watcher's flush timing
  packages/core/computedAsync/index.ts
Labels: enhancement, size:S, lgtm

#4751 fix(computedAsync): return `ComputedRef<T>` type when `lazy: true`
  packages/core/computedAsync/index.test.ts
  packages/core/computedAsync/index.ts
Labels: size:M, lgtm

#4745 fix(useFullscreen): get the correct initial state while mounted
  packages/core/useFullscreen/index.ts
Labels: size:XS, lgtm

#4750 feat(watchOnce): use vue's native once behaviour
  packages/shared/watchOnce/index.md
  packages/shared/watchOnce/index.ts
Labels: size:M, lgtm

#4699 docs(useGamepad): resolve SSR detection issues with <ClientOnly>
  packages/core/useGamepad/demo.client.vue
  packages/core/useGamepad/index.md
Labels: size:XS, lgtm

#4727 feat(useScroll): add missing measure documentation
  packages/core/useScroll/demo.vue
  packages/core/useScroll/index.md
Labels: documentation, size:M, lgtm

#4749 feat(useStyleTag): support passing `nonce`
  packages/core/useStyleTag/index.ts
Labels: size:XS, lgtm

#4728 fix(fromEvent): fix type error of element reference
  packages/rxjs/README.md
  packages/rxjs/from/_demo.vue
  packages/rxjs/from/index.md
  packages/rxjs/from/index.ts
  packages/rxjs/toObserver/_demo.vue
  packages/rxjs/toObserver/index.md
Labels: size:S, lgtm

#4731 fix(useMagicKeys): correctly clear current pressed keys when releasing Shift
  packages/core/useMagicKeys/index.ts
Labels: size:S, lgtm

#4755 refactor(vOnClickOutside): use weakMap for stop function instead of mutating element
  packages/core/onClickOutside/directive.ts
Labels: directive, size:S, lgtm

#4702 docs: link demos to playground (beta)
  package.json
  packages/.vitepress/plugins/markdownTransform.ts
  packages/.vitepress/theme/styles/demo.css
  packages/.vitepress/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: documentation, size:M, lgtm

#4768 feat(useNow): expose immediate option
  packages/core/useNow/index.test.ts
  packages/core/useNow/index.ts
Labels: enhancement, size:S, lgtm

#4765 fix(useFetch): use `globalThis.fetch` when `defaultWindow.fetch` not exist
  packages/core/useFetch/index.ts
Labels: size:XS, lgtm

#4760 fix(useSortable): fix type misalignment
  packages/integrations/useSortable/index.ts
Labels: size:XS

#4769 docs(pwa): fix 404 navigation errors when using search
  .gitignore
  packages/.vitepress/config.ts
  packages/.vitepress/plugins/pwa-virtual.ts
  packages/.vitepress/shims.d.ts
  packages/.vitepress/sw.ts
  packages/.vitepress/vite.config.ts
Labels: documentation, size:L, lgtm
