Repository vueuse/vueuse, pull requests merged in 2025-09, with the labels that each got.

#4923 fix(useThrottleFn)!: align with traditional throttle behavior
  packages/shared/useThrottleFn/index.test.ts
  packages/shared/utils/filters.ts
Labels: BREAKING CHANGE, size:M, lgtm

#4886 feat(useSwipe)!: remove isPassiveEventSupported
  packages/core/useSwipe/index.ts
Labels: BREAKING CHANGE, size:XS, lgtm

#5002 test(useTilte): add test to cover all features
  packages/core/useTitle/index.test.ts
Labels: size:M, lgtm

#4959 types: enhance injectLocal and provideLocal types for better type safety
  packages/shared/injectLocal/index.ts
  packages/shared/provideLocal/index.ts
  packages/shared/provideLocal/map.ts
  packages/shared/utils/types.ts
Labels: enhancement, size:S, lgtm

#4844 test: refactor base url
  packages/.test/mockServer.ts
  packages/core/useFetch/index.test.ts
Labels: size:M, lgtm

#5017 docs(useFetch): correct spelling error in useFetch documentation
  packages/core/useFetch/index.md
Labels: documentation, size:XS, lgtm

#4644 feat(refManualReset): new function
  packages/shared/index.ts
  packages/shared/refManualReset/demo.vue
  packages/shared/refManualReset/index.md
  packages/shared/refManualReset/index.test.ts
  packages/shared/refManualReset/index.ts
  test/exports/core.yaml
  test/exports/shared.yaml
Labels: enhancement, new function, direction: approved, size:L, lgtm

#5021 build: simplify baseConfig setup and improve `dist` output
  tsdown.config.ts
Labels: build tools, size:M, lgtm

#5009 feat!: deprecate alias exports in favor of original function names
  packages/core/computedAsync/index.ts
  packages/core/onClickOutside/directive.ts
  packages/core/onLongPress/directive.ts
  packages/math/logicAnd/index.ts
  packages/math/logicNot/index.ts
  packages/math/logicOr/index.ts
  packages/shared/computedEager/index.ts
  packages/shared/computedWithControl/index.ts
  packages/shared/reactify/index.ts
  packages/shared/refAutoReset/index.ts
  packages/shared/refDebounced/index.ts
  packages/shared/refThrottled/index.ts
  packages/shared/refWithControl/index.ts
  packages/shared/watchDebounced/index.ts
  packages/shared/watchIgnorable/index.ts
  packages/shared/watchPausable/index.ts
  packages/shared/watchThrottled/index.ts
Labels: size:M, lgtm

#4896 feat(watch): update watch return typo in watchExtractedObservable, watchDebounced, watchDeep, watchImmediate, watchOnce, watchThrottled and watchWithFilter
  packages/guidelines.md
  packages/rxjs/watchExtractedObservable/index.ts
  packages/shared/watchDebounced/index.ts
  packages/shared/watchDeep/index.ts
  packages/shared/watchImmediate/index.ts
  packages/shared/watchOnce/index.ts
  packages/shared/watchThrottled/index.ts
  packages/shared/watchWithFilter/index.ts
Labels: size:M, lgtm

#4961 chore: update flush option to use WatchOptionFlush type across multipl…
  packages/core/computedAsync/index.ts
  packages/core/useRefHistory/index.md
  packages/core/useRefHistory/index.ts
  packages/shared/syncRefs/index.md
  packages/shared/until/index.ts
  packages/shared/utils/types.ts
  packages/shared/watchIgnorable/index.md
Labels: size:S, lgtm

#4965 fix(useFullscreen): specify return types for request, exit, and enabl…
  packages/core/useFullscreen/index.ts
Labels: size:XS, lgtm

#4997 feat(createSharedComposable)!: return only the sharedComposable on client side
  .github/workflows/ci.yml
  package.json
  packages/shared/createSharedComposable/index.md
  packages/shared/createSharedComposable/index.server.test.ts
  packages/shared/createSharedComposable/index.test.ts
  packages/shared/createSharedComposable/index.ts
  packages/shared/utils/index.server.test.ts
  vitest.config.ts
Labels: enhancement, size:M, lgtm

#4962 fix: update return type of createReusableTemplate and createTemplateP…
  packages/core/createReusableTemplate/index.ts
  packages/core/createTemplatePromise/index.ts
Labels: size:XS, lgtm

#5041 docs: update info block background color
  packages/.vitepress/theme/styles/vars.css
Labels: documentation, size:XS

#5048 fix(useShare): improve the accuracy of sharing logic
  packages/core/useShare/index.ts
Labels: size:XS, lgtm

#5047 fix(useAsyncState): track latest execution to avoid newer results being replaced by outdated ones
  packages/core/useAsyncState/index.test.ts
  packages/core/useAsyncState/index.ts
Labels: size:M, lgtm

#5050 fix(shared): support provideLocal/injectLocal in vapor mode
  packages/shared/injectLocal/index.ts
  packages/shared/provideLocal/index.ts
  packages/shared/provideLocal/map.ts
Labels: size:S, lgtm

#5060 fix: update parameter types to use ComponentInternalInstance in lifec…
  packages/shared/tryOnBeforeMount/index.ts
  packages/shared/tryOnBeforeUnmount/index.ts
  packages/shared/tryOnMounted/index.ts
  packages/shared/tryOnUnmounted/index.ts
  packages/shared/utils/vue.ts
Labels: size:S, lgtm

#4926 ci: use Turborepo for caching to speed up build scripts
  .gitignore
  package.json
  packages/metadata/turbo.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: build tools, size:M, lgtm

#5073 chore(createTemplatePromise): add basic usage test case
  packages/core/createTemplatePromise/index.test.ts
Labels: size:M
