Repository vueuse/vueuse, pull requests merged in 2025-08, with the labels that each got.

#4943 feat(computedAsync): use globalThis.reportError as default onError
  packages/core/computedAsync/index.test.ts
  packages/core/computedAsync/index.ts
Labels: enhancement, size:S, lgtm

#4948 chore(metadata): add spellWhiteList and update description formatting logic
  packages/metadata/scripts/update.ts
Labels: size:XS, lgtm

#4951 feat(useAsyncState)!: set globalThis.reportError as default onError
  packages/core/useAsyncState/index.test.ts
  packages/core/useAsyncState/index.ts
Labels: enhancement, size:S, lgtm

#4952 test(useMagicKeys): add tests
  packages/core/useMagicKeys/index.test.ts
Labels: size:L, lgtm

#4970 docs: recommend using tryOnScopeDispose instead of tryOnUnmounted
  packages/guidelines.md
Labels: documentation, size:XS

#4973 perf(usePreferredLanguages): use shallowRef for better performance
  packages/core/usePreferredLanguages/index.ts
Labels: size:S, lgtm

#4953 feat(useEventSource): add `serializer`
  packages/core/useEventSource/index.md
  packages/core/useEventSource/index.test.ts
  packages/core/useEventSource/index.ts
Labels: enhancement, size:M, lgtm

#4980 perf(usePointer): use shallowRef for better performance
  packages/core/usePointer/index.ts
Labels: enhancement, size:XS, lgtm

#4992 feat(useAsyncState): allow initial value to be a ref
  packages/core/useAsyncState/index.test.ts
  packages/core/useAsyncState/index.ts
Labels: enhancement, size:S, lgtm

#4979 feat(onLongPress): allow function as value in delay
  packages/core/onLongPress/index.test.ts
  packages/core/onLongPress/index.ts
Labels: enhancement, size:S, lgtm

#4969 fix(useUrlSearchParams): restore proper history and navigation behavior
  packages/core/useUrlSearchParams/index.test.ts
  packages/core/useUrlSearchParams/index.ts
Labels: size:L, lgtm

#4994 chore: add breakpoint debugging config for VS Code
  .vscode/launch.json
  packages/.vitepress/vite.config.ts
Labels: build tools, size:S, lgtm

#4966 fix(types): update type casting for watch functions to use WatchSource<T>
  packages/rxjs/useExtractedObservable/index.ts
  packages/rxjs/watchExtractedObservable/index.ts
  packages/shared/watchDeep/index.ts
  packages/shared/watchImmediate/index.ts
  packages/shared/watchOnce/index.ts
Labels: size:S, lgtm

#5000 test(onLongPress): use custom timer in test assertion
  packages/core/onLongPress/index.test.ts
Labels: size:XS, lgtm
